from collections.abc import Iterable, Sequence
from typing import Any

def figure(*args: Any, **kwargs: Any) -> Any: ...
def plot(x: Iterable[Any], y: Iterable[Any] | None = ...) -> Any: ...
def axhline(y: float, *args: Any, **kwargs: Any) -> Any: ...
def scatter(x: Sequence[Any], y: Sequence[Any], *args: Any, **kwargs: Any) -> Any: ...
def title(s: str) -> Any: ...
def xlabel(s: str) -> Any: ...
def ylabel(s: str) -> Any: ...
def savefig(fname: str, *args: Any, **kwargs: Any) -> Any: ...
def close() -> None: ...
