name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (ruff)
        run: ruff check .

      - name: Typecheck (mypy)
        run: mypy .

      - name: Tests (pytest)
        run: pytest

      - name: Build Day-2 artifacts (proof + resonance)
        run: |
          python demo_day2.py --proof --resonance

      - name: Upload artifacts (images, CSV, Lean, TeX)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: day2-artifacts
          path: |
            docs/resonance_wave.png
            docs/resonance_states.csv
            docs/proof_lean_sketch.lean
            docs/proof_draft.tex
          if-no-files-found: warn
